import XCTest

/// Covers session persistence and title lifecycle.
///
/// The decoding tests are the most important in the suite: `ChatSession` has
/// gained fields across several changes (`artifacts`, `titleRevisions`,
/// `titleIsUserSet`, `digest`, `digestedThroughIndex`), and synthesized `Codable`
/// throws `keyNotFound` on a missing key. A regression here wouldn't be cosmetic —
/// it would make every previously saved conversation fail to load and vanish from
/// the sidebar.
final class ChatSessionTests: XCTestCase {

    private func decode(_ json: String) throws -> ChatSession {
        try JSONDecoder().decode(ChatSession.self, from: Data(json.utf8))
    }

    // MARK: - Backward-compatible decoding

    func testSessionSavedBeforeNewFieldsExistedStillLoads() throws {
        let json = """
        {"id":"\(UUID().uuidString)","title":"Old Chat","modelName":"llama3:8b",
         "messages":[
           {"id":"\(UUID().uuidString)","role":"user","content":"make me a logo for Kairos","isImage":false,"attachments":[]},
           {"id":"\(UUID().uuidString)","role":"assistant","content":"","isImage":true,"imageData":"SGVsbG8=","attachments":[]}
         ],
         "createdAt":760000000,"updatedAt":760000000,"titleIsAutoGenerated":true}
        """
        let session = try decode(json)

        XCTAssertEqual(session.messages.count, 2, "Existing conversations must survive the schema change.")
        XCTAssertEqual(session.titleRevisions, 0)
        XCTAssertFalse(session.titleIsUserSet)
        XCTAssertEqual(session.digest, "")
        XCTAssertEqual(session.digestedThroughIndex, 0)
    }

    func testLedgerIsBackfilledForPreExistingConversations() throws {
        let json = """
        {"id":"\(UUID().uuidString)","title":"Old","modelName":"m",
         "messages":[
           {"id":"\(UUID().uuidString)","role":"user","content":"make me a logo for Kairos","isImage":false,"attachments":[]},
           {"id":"\(UUID().uuidString)","role":"assistant","content":"","isImage":true,"imageData":"SGVsbG8=","attachments":[]}
         ],
         "createdAt":1,"updatedAt":1}
        """
        let session = try decode(json)

        // Old chats gain working artifact tracking rather than being permanently
        // second-class on the brittle keyword path.
        XCTAssertEqual(session.artifacts.count, 1)
        XCTAssertEqual(session.artifacts.first?.kind, .generatedImage)
        XCTAssertEqual(session.artifacts.first?.label.contains("Kairos"), true)
    }

    func testVeryOldSchemaWithoutTitleFlagDecodes() throws {
        let json = """
        {"id":"\(UUID().uuidString)","title":"X","modelName":"m","messages":[],"createdAt":1,"updatedAt":1}
        """
        XCTAssertNoThrow(try decode(json))
    }

    func testCustomisedTitleIsTreatedAsUserSet() throws {
        let json = """
        {"id":"\(UUID().uuidString)","title":"My Chat","modelName":"m","messages":[],
         "createdAt":1,"updatedAt":1,"titleIsAutoGenerated":false}
        """
        let session = try decode(json)

        // Sessions predate explicit user-set tracking, so it's inferred — which
        // preserves a title the user had already customised.
        XCTAssertTrue(session.titleIsUserSet)
        XCTAssertFalse(session.shouldReviseTitle)
    }

    func testStoredDigestIndexBeyondMessageCountIsClamped() throws {
        let json = """
        {"id":"\(UUID().uuidString)","title":"X","modelName":"m",
         "messages":[{"id":"\(UUID().uuidString)","role":"user","content":"hi","isImage":false,"attachments":[]}],
         "createdAt":1,"updatedAt":1,"digestedThroughIndex":9999}
        """
        let session = try decode(json)
        XCTAssertLessThanOrEqual(
            session.digestedThroughIndex, session.messages.count,
            "An out-of-range index would make compaction planning slice out of bounds."
        )
    }

    func testRoundTripPreservesArtifacts() throws {
        var session = ChatSession(modelName: "m")
        session.recordArtifact(
            SessionArtifact(kind: .generatedImage, messageId: UUID(), label: "a logo for Kairos")
        )
        let restored = try JSONDecoder().decode(
            ChatSession.self, from: JSONEncoder().encode(session)
        )
        XCTAssertEqual(restored.artifacts.count, 1)
    }

    // MARK: - Ledger mutation

    func testRecordingIsIdempotent() {
        var session = ChatSession(modelName: "m")
        let messageId = UUID()
        for _ in 0..<5 {
            session.recordArtifact(
                SessionArtifact(kind: .generatedImage, messageId: messageId, label: "logo")
            )
        }
        // Streaming, retries and re-persist cycles can all re-run the recording
        // path for one logical event.
        XCTAssertEqual(session.artifacts.count, 1)
    }

    func testPruningDropsOnlyOrphanedArtifacts() {
        var session = ChatSession(modelName: "m")
        let live = DisplayMessage(role: "assistant", content: "", isImage: true, imageData: Data([1]))
        session.messages = [live]
        session.recordArtifact(SessionArtifact(kind: .generatedImage, messageId: live.id, label: "kept"))
        session.recordArtifact(SessionArtifact(kind: .generatedImage, messageId: UUID(), label: "orphan"))

        session.pruneArtifacts()

        XCTAssertEqual(session.artifacts.map(\.label), ["kept"])
    }

    func testAttachmentsAreBackfilledByKind() {
        var session = ChatSession(modelName: "m")
        session.messages = [
            DisplayMessage(role: "user", content: "look", isImage: false, attachments: [
                MessageAttachment(fileName: "shot.png", kind: .image, imageData: Data([1])),
                MessageAttachment(fileName: "notes.txt", kind: .textFile, extractedText: "hi")
            ])
        ]
        session.backfillArtifacts()

        XCTAssertTrue(session.artifacts.contains { $0.kind == .attachedImage && $0.label == "shot.png" })
        XCTAssertTrue(session.artifacts.contains { $0.kind == .document && $0.label == "notes.txt" })
        XCTAssertEqual(SessionArtifact.visuals(in: session.artifacts).count, 1)
    }

    // MARK: - Title lifecycle

    private func session(withExchanges count: Int) -> ChatSession {
        var session = ChatSession(modelName: "m")
        session.titleIsAutoGenerated = false
        for index in 0..<count {
            session.messages.append(DisplayMessage(role: "user", content: "q\(index)", isImage: false))
            session.messages.append(DisplayMessage(role: "assistant", content: "a\(index)", isImage: false))
        }
        return session
    }

    func testRevisionTriggersAtFirstCheckpoint() {
        XCTAssertTrue(session(withExchanges: 4).shouldReviseTitle)
    }

    /// Revising at exactly the checkpoint used to leave this true on the next
    /// turn too, so it fired again immediately and burned the cap in consecutive
    /// messages — the exact churn the cap exists to prevent.
    func testRevisionDoesNotRepeatImmediatelyAfterApplying() {
        var session = self.session(withExchanges: 4)
        session.applyRevisedTitle("Brand Logo Design")

        XCTAssertEqual(session.title, "Brand Logo Design")
        XCTAssertEqual(session.titleRevisions, 1)
        XCTAssertFalse(session.shouldReviseTitle)
    }

    func testRevisionCapIsRespected() {
        var session = self.session(withExchanges: 20)
        session.titleRevisions = ChatSession.titleRevisionLimit
        XCTAssertFalse(session.shouldReviseTitle)
    }

    func testUserTitleIsNeverOverwritten() {
        var session = ChatSession(modelName: "m")
        session.setUserTitle("Mine")

        XCTAssertFalse(session.shouldReviseTitle)
        session.applyRevisedTitle("Override")
        XCTAssertEqual(session.title, "Mine")
    }

    func testDigestLabelsImageTurnsExplicitly() {
        var session = ChatSession(modelName: "m")
        session.messages = [
            DisplayMessage(role: "user", content: "make a logo", isImage: false),
            DisplayMessage(role: "assistant", content: "", isImage: true, imageData: Data([1]))
        ]
        let digest = session.titleDigest()

        XCTAssertTrue(digest.contains("make a logo"))
        XCTAssertTrue(
            digest.contains("[generated an image]"),
            "Image turns have empty text, so a chat that became image work would otherwise look stalled."
        )
    }

    func testPromptLabelIsCondensedToFirstSentence() {
        XCTAssertEqual(
            ChatSession.label(fromPrompt: "A logo for Kairos. Visual concept: time"),
            "A logo for Kairos"
        )
        XCTAssertLessThanOrEqual(
            (ChatSession.label(fromPrompt: String(repeating: "z", count: 200)) ?? "").count, 61
        )
        XCTAssertNil(ChatSession.label(fromPrompt: nil))
    }
}
