/*
 * NativAI - Standalone Local LLM Manager for macOS
 * Copyright (C) 2026 Muhammad Abdul Rafey
 * Licensed under the GNU General Public License v3.0 (GPLv3).
 */

import Foundation

/// A persistent conversation session containing messages, artifacts, and title lifecycle state.
public struct ChatSession: Identifiable, Codable, Equatable, Sendable {
    public static let titleRevisionLimit: Int = 3

    public var id: UUID
    public var title: String
    public var modelName: String
    public var messages: [DisplayMessage]
    public var createdAt: Date
    public var updatedAt: Date

    public var titleIsAutoGenerated: Bool
    public var titleIsUserSet: Bool
    public var titleRevisions: Int
    public var digest: String
    public var digestedThroughIndex: Int
    public var artifacts: [SessionArtifact]

    public init(
        id: UUID = UUID(),
        title: String = "New Chat",
        modelName: String,
        messages: [DisplayMessage] = [],
        createdAt: Date = Date(),
        updatedAt: Date = Date(),
        titleIsAutoGenerated: Bool = true,
        titleIsUserSet: Bool = false,
        titleRevisions: Int = 0,
        digest: String = "",
        digestedThroughIndex: Int = 0,
        artifacts: [SessionArtifact] = []
    ) {
        self.id = id
        self.title = title
        self.modelName = modelName
        self.messages = messages
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.titleIsAutoGenerated = titleIsAutoGenerated
        self.titleIsUserSet = titleIsUserSet
        self.titleRevisions = titleRevisions
        self.digest = digest
        self.digestedThroughIndex = digestedThroughIndex
        self.artifacts = artifacts
    }

    public enum CodingKeys: String, CodingKey {
        case id, title, modelName, messages, createdAt, updatedAt
        case titleIsAutoGenerated, titleIsUserSet, titleRevisions
        case digest, digestedThroughIndex, artifacts
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.id = try container.decodeIfPresent(UUID.self, forKey: .id) ?? UUID()
        self.title = try container.decodeIfPresent(String.self, forKey: .title) ?? "New Chat"
        self.modelName = try container.decodeIfPresent(String.self, forKey: .modelName) ?? ""
        self.messages = try container.decodeIfPresent([DisplayMessage].self, forKey: .messages) ?? []
        self.createdAt = try container.decodeIfPresent(Date.self, forKey: .createdAt) ?? Date()
        self.updatedAt = try container.decodeIfPresent(Date.self, forKey: .updatedAt) ?? Date()

        let autoGenerated = try container.decodeIfPresent(Bool.self, forKey: .titleIsAutoGenerated) ?? true
        self.titleIsAutoGenerated = autoGenerated

        if let userSet = try container.decodeIfPresent(Bool.self, forKey: .titleIsUserSet) {
            self.titleIsUserSet = userSet
        } else {
            // Infer from legacy titleIsAutoGenerated flag
            self.titleIsUserSet = !autoGenerated
        }

        self.titleRevisions = try container.decodeIfPresent(Int.self, forKey: .titleRevisions) ?? 0
        self.digest = try container.decodeIfPresent(String.self, forKey: .digest) ?? ""

        let rawDigestedIndex = try container.decodeIfPresent(Int.self, forKey: .digestedThroughIndex) ?? 0
        self.digestedThroughIndex = min(rawDigestedIndex, self.messages.count)

        if let decodedArtifacts = try container.decodeIfPresent([SessionArtifact].self, forKey: .artifacts) {
            self.artifacts = decodedArtifacts
        } else {
            self.artifacts = []
            self.backfillArtifacts()
        }
    }

    public var shouldReviseTitle: Bool {
        guard !titleIsUserSet else { return false }
        guard titleRevisions < Self.titleRevisionLimit else { return false }

        let userCount = messages.filter { $0.role == "user" }.count
        let assistantCount = messages.filter { $0.role == "assistant" }.count
        let exchanges = min(userCount, assistantCount)

        if titleRevisions == 0 {
            return exchanges >= 4
        } else if titleRevisions == 1 {
            return exchanges >= 10
        } else if titleRevisions == 2 {
            return exchanges >= 20
        }
        return false
    }

    public var needsGeneratedTitle: Bool {
        titleIsAutoGenerated && !titleIsUserSet
    }

    public mutating func refreshAutoTitle() {
        guard titleIsAutoGenerated && !titleIsUserSet else { return }
        if let first = messages.first(where: { $0.role == "user" }),
           let condensed = Self.label(fromPrompt: first.content) {
            title = condensed
        }
    }

    public mutating func lockTitle(_ newTitle: String) {
        guard !titleIsUserSet else { return }
        title = newTitle
        titleIsAutoGenerated = false
    }

    public mutating func recordArtifact(_ artifact: SessionArtifact) {
        if !artifacts.contains(where: { $0.messageId == artifact.messageId && $0.label == artifact.label }) {
            artifacts.append(artifact)
        }
    }

    public mutating func pruneArtifacts() {
        let liveIds = Set(messages.map(\.id))
        artifacts.removeAll { !liveIds.contains($0.messageId) }
    }

    public mutating func backfillArtifacts() {
        for (index, message) in messages.enumerated() {
            if message.isImage {
                let priorPrompt = messages[..<index].reversed().first(where: { $0.role == "user" })?.content
                let label = Self.label(fromPrompt: priorPrompt) ?? "generated image"
                recordArtifact(SessionArtifact(
                    kind: .generatedImage,
                    messageId: message.id,
                    label: label
                ))
            }
            for attachment in message.attachments {
                let kind: SessionArtifact.Kind = (attachment.kind == .image) ? .attachedImage : .document
                recordArtifact(SessionArtifact(
                    kind: kind,
                    messageId: message.id,
                    label: attachment.fileName
                ))
            }
        }
    }

    public mutating func setUserTitle(_ newTitle: String) {
        self.title = newTitle
        self.titleIsUserSet = true
        self.titleIsAutoGenerated = false
    }

    public mutating func applyRevisedTitle(_ newTitle: String) {
        guard !titleIsUserSet else { return }
        self.title = newTitle
        self.titleRevisions += 1
    }

    public func titleDigest() -> String {
        var lines: [String] = []
        for msg in messages {
            if msg.isImage {
                lines.append("\(msg.role): [generated an image]")
            } else if !msg.content.isEmpty {
                lines.append("\(msg.role): \(msg.content)")
            }
        }
        return lines.joined(separator: "\n")
    }

    public static func label(fromPrompt: String?) -> String? {
        guard let prompt = fromPrompt?.trimmingCharacters(in: .whitespacesAndNewlines), !prompt.isEmpty else {
            return nil
        }
        let delimiters: [Character] = [".", "!", "?", "\n"]
        var sentence = prompt
        if let idx = prompt.firstIndex(where: { delimiters.contains($0) }) {
            sentence = String(prompt[..<idx]).trimmingCharacters(in: .whitespaces)
        }
        if sentence.count > 60 {
            sentence = String(sentence.prefix(60)).trimmingCharacters(in: .whitespaces)
        }
        return sentence.isEmpty ? nil : sentence
    }
}
