/*
 * NativAI - Standalone Local LLM Manager for macOS
 * Copyright (C) 2026 Muhammad Abdul Rafey
 * Licensed under the GNU General Public License v3.0 (GPLv3).
 */

import Foundation

/// A single saved conversation. Persisted locally as JSON so chat history
/// survives app restarts, and can be deleted individually to free disk space.
struct ChatSession: Identifiable, Codable, Equatable {
    let id: UUID
    var title: String
    var modelName: String
    var messages: [DisplayMessage]
    var createdAt: Date
    var updatedAt: Date
    /// True as long as the user hasn't manually renamed this chat. Once
    /// false, refreshAutoTitle() stops overwriting the title — needed so a
    /// dynamically-updating title (see below) doesn't clobber a name the
    /// user deliberately set.
    var titleIsAutoGenerated: Bool
    /// Typed record of the images and documents in this conversation.
    ///
    /// Kept as explicit state rather than re-derived from `messages` each turn,
    /// because inferring "is there an image here and is the user asking about
    /// it?" from prose is precisely what made routing fragile (see
    /// SessionArtifact for the full history). Recorded once, when unambiguous.
    var artifacts: [SessionArtifact]

    /// How many times the auto-generated title has been rewritten.
    ///
    /// Capped (see `titleRevisionLimit`) because a title that keeps changing is
    /// worse than one that's slightly stale: the sidebar is a spatial memory
    /// aid, and renaming entries out from under the user destroys it. Two
    /// revisions is enough to catch a conversation that genuinely changed
    /// subject early on, without churning forever.
    var titleRevisions: Int = 0

    /// True once the user has renamed the chat themselves. A manual title is
    /// never overwritten by generation or revision.
    var titleIsUserSet: Bool = false

    static let titleRevisionLimit = 2

    /// Running prose summary of turns too old to send verbatim.
    ///
    /// Long conversations exceed any model's context window, and `TokenBudget`
    /// responds by dropping the oldest turns. This is where that dropped
    /// material goes instead, so a fact established early in a long chat is
    /// still available late in it.
    var digest: String = ""

    /// How many leading messages are represented in `digest`.
    ///
    /// Only ever moves forward. Compaction is append-only precisely so a summary
    /// is never re-summarized — each such pass loses detail, and after a few
    /// rounds the result is vague and confidently wrong.
    var digestedThroughIndex: Int = 0

    init(id: UUID = UUID(), title: String = "New Chat", modelName: String, messages: [DisplayMessage] = [], createdAt: Date = Date(), updatedAt: Date = Date(), titleIsAutoGenerated: Bool = true, artifacts: [SessionArtifact] = []) {
        self.id = id
        self.title = title
        self.modelName = modelName
        self.messages = messages
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.titleIsAutoGenerated = titleIsAutoGenerated
        self.artifacts = artifacts
    }

    /// Custom decoding so chats saved before the artifact ledger existed still
    /// load. Synthesized Codable would throw `keyNotFound` on the missing
    /// `artifacts` key and silently wipe the user's entire chat history from
    /// the sidebar — the same trap `ModelEntry.supportsVision` had to work
    /// around when it was added to the catalog schema.
    ///
    /// Old sessions decode with an empty ledger and then backfill on load, so
    /// existing conversations gain working artifact tracking rather than being
    /// permanently second-class.
    init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        id = try container.decode(UUID.self, forKey: .id)
        title = try container.decode(String.self, forKey: .title)
        modelName = try container.decode(String.self, forKey: .modelName)
        messages = try container.decode([DisplayMessage].self, forKey: .messages)
        createdAt = try container.decode(Date.self, forKey: .createdAt)
        updatedAt = try container.decode(Date.self, forKey: .updatedAt)
        titleIsAutoGenerated = try container.decodeIfPresent(Bool.self, forKey: .titleIsAutoGenerated) ?? true
        artifacts = try container.decodeIfPresent([SessionArtifact].self, forKey: .artifacts) ?? []
        titleRevisions = try container.decodeIfPresent(Int.self, forKey: .titleRevisions) ?? 0
        digest = try container.decodeIfPresent(String.self, forKey: .digest) ?? ""
        // Clamped on load: a stored index greater than the message count (from a
        // hand-edited file, or messages deleted after digesting) would make
        // `plan` slice out of bounds. Treating it as "everything is digested" is
        // the safe reading — it degrades to plain truncation rather than crashing.
        let storedIndex = try container.decodeIfPresent(Int.self, forKey: .digestedThroughIndex) ?? 0
        digestedThroughIndex = min(max(0, storedIndex), messages.count)
        // Older sessions predate explicit user-set tracking. Inferring it from
        // `titleIsAutoGenerated == false` preserves the intent of any title the
        // user had already customised, so revision can't overwrite it.
        titleIsUserSet = try container.decodeIfPresent(Bool.self, forKey: .titleIsUserSet)
            ?? !(try container.decodeIfPresent(Bool.self, forKey: .titleIsAutoGenerated) ?? true)
        if artifacts.isEmpty {
            backfillArtifacts()
        }
    }

    /// Auto-derives a short title ONCE, from the first substantive user
    /// message (over a minimum length, skipping short openers like "Hi" or
    /// "ok"), then locks it in permanently by flipping titleIsAutoGenerated
    /// to false. Previously this re-ran on every send() call and kept
    /// overwriting the title with whatever the most recent message was,
    /// which meant the chat name kept changing throughout a conversation
    /// instead of settling on one static name — this fixes that by only
    /// ever setting the title the first time a real topic appears.
    /// Sets a PROVISIONAL title immediately from the first substantive user
    /// message, so the sidebar never sits on "New Chat" while waiting on the
    /// network. Deliberately does NOT lock the title — ChatViewModel replaces
    /// this with a proper LLM-generated title once the first reply arrives,
    /// then locks it via `lockTitle(_:)`.
    ///
    /// Previously this both truncated AND locked, which is why chats were
    /// permanently named things like "I am planning on building a clothing
    /// bra…". The truncation is now only a placeholder.
    mutating func refreshAutoTitle() {
        guard titleIsAutoGenerated else { return }
        let userMessages = messages.filter { $0.role == "user" }
        guard !userMessages.isEmpty else { return }

        let substantive = userMessages.filter { $0.content.trimmingCharacters(in: .whitespacesAndNewlines).count > 10 }
        // Unlike before, fall back to the first message regardless of count —
        // a user sending only short messages ("hi", "ok", "thx") would
        // otherwise stay on "New Chat" until their fourth turn.
        guard let source = substantive.first ?? userMessages.first else { return }

        let trimmed = source.content.trimmingCharacters(in: .whitespacesAndNewlines)
        title = String(trimmed.prefix(40)) + (trimmed.count > 40 ? "…" : "")
    }

    /// Applies the final LLM-generated title and locks it permanently, so it
    /// never changes again for the life of the conversation and can still be
    /// overridden by a manual rename.
    mutating func lockTitle(_ newTitle: String) {
        let trimmed = newTitle.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        title = trimmed
        titleIsAutoGenerated = false
    }

    /// True when this session still needs its one-time LLM title. Gated on
    /// having a real exchange (a user message AND a non-empty assistant reply)
    /// so we don't burn a call summarising a half-finished turn.
    var needsGeneratedTitle: Bool {
        guard titleIsAutoGenerated else { return false }
        guard messages.contains(where: { $0.role == "user" }) else { return false }
        return messages.contains {
            $0.role == "assistant" && !$0.content.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
        }
    }

    // MARK: - Title revision

    /// Whether the title should be re-checked against how the conversation has
    /// actually developed.
    ///
    /// Triggers at fixed exchange counts rather than on every turn: a revision
    /// costs a model call, and the value is concentrated early, when a chat is
    /// most likely to have drifted from its opening question. Never fires for a
    /// user-set title.
    ///
    /// Gated on `titleRevisions` matching the checkpoint *index*, not merely
    /// being under the cap. Without that, revising at exactly 4 exchanges left
    /// this true on the following turn too, so it would fire again immediately
    /// and burn through the cap in consecutive messages — the exact churn the
    /// cap exists to prevent.
    var shouldReviseTitle: Bool {
        guard !titleIsUserSet else { return false }
        guard titleRevisions < Self.titleRevisionLimit else { return false }
        let exchanges = messages.filter { $0.role == "assistant" && !$0.content.isEmpty }.count
        // Each checkpoint belongs to one revision slot: the first revision can
        // only happen at >=4 exchanges, the second only at >=10.
        let checkpoints = [4, 10]
        guard titleRevisions < checkpoints.count else { return false }
        return exchanges >= checkpoints[titleRevisions]
    }

    /// Compact transcript for the title reviser: what the conversation is
    /// actually about, rather than only how it opened.
    ///
    /// Includes user turns and a short slice of each reply. Generated-image
    /// turns are labelled explicitly, since their message text is empty and a
    /// conversation that became image work would otherwise look like it stalled.
    func titleDigest(maxCharacters: Int = 1200) -> String {
        var lines: [String] = []
        for message in messages {
            if message.isImage {
                lines.append("Assistant: [generated an image]")
                continue
            }
            let text = message.content.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { continue }
            let role = message.role == "user" ? "User" : "Assistant"
            lines.append("\(role): \(String(text.prefix(200)))")
        }
        let joined = lines.joined(separator: "\n")
        return joined.count > maxCharacters ? String(joined.suffix(maxCharacters)) : joined
    }

    /// Applies a revised title, counting it against the cap.
    mutating func applyRevisedTitle(_ newTitle: String) {
        guard !titleIsUserSet else { return }
        title = newTitle
        titleRevisions += 1
        titleIsAutoGenerated = false
    }

    /// Records that the user renamed this chat, permanently disabling automatic
    /// titling for it.
    mutating func setUserTitle(_ newTitle: String) {
        let trimmed = newTitle.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return }
        title = trimmed
        titleIsUserSet = true
        titleIsAutoGenerated = false
    }

    // MARK: - Artifact ledger

    /// Records an artifact, ignoring duplicates for the same message+kind.
    ///
    /// Idempotent on purpose: streaming, retries and re-persist cycles can all
    /// re-run the recording path for one logical event, and a ledger that
    /// double-counts would make "the second image" point at a phantom.
    mutating func recordArtifact(_ artifact: SessionArtifact) {
        let alreadyPresent = artifacts.contains {
            $0.messageId == artifact.messageId && $0.kind == artifact.kind
        }
        guard !alreadyPresent else { return }
        artifacts.append(artifact)
    }

    /// Drops ledger entries whose backing message no longer exists, so a
    /// deleted message can't leave the router describing an image that isn't
    /// there any more.
    mutating func pruneArtifacts() {
        let liveIds = Set(messages.map { $0.id })
        artifacts.removeAll { !liveIds.contains($0.messageId) }
    }

    /// Reconstructs the ledger from existing messages, for sessions saved
    /// before the ledger existed.
    ///
    /// Labels are necessarily coarser here than for newly-recorded artifacts —
    /// the generating prompt wasn't stored at the time, so the preceding user
    /// message is the best available description. That's a deliberate accuracy
    /// tradeoff: a slightly vague label still resolves the common "make it
    /// bluer" follow-up correctly, whereas no ledger at all would leave every
    /// pre-existing conversation stuck on the old brittle keyword path.
    mutating func backfillArtifacts() {
        var rebuilt: [SessionArtifact] = []
        for (index, message) in messages.enumerated() {
            if message.isImage && message.imageData != nil {
                // The request that produced it is the nearest preceding user turn.
                let precedingPrompt = messages[..<index].last { $0.role == "user" }?.content
                rebuilt.append(SessionArtifact(
                    kind: .generatedImage,
                    messageId: message.id,
                    label: Self.label(fromPrompt: precedingPrompt) ?? "a generated image",
                    sourcePrompt: precedingPrompt,
                    createdAt: createdAt
                ))
            }
            for attachment in message.attachments {
                switch attachment.kind {
                case .image:
                    rebuilt.append(SessionArtifact(
                        kind: .attachedImage,
                        messageId: message.id,
                        label: attachment.fileName,
                        createdAt: createdAt
                    ))
                case .textFile:
                    rebuilt.append(SessionArtifact(
                        kind: .document,
                        messageId: message.id,
                        label: attachment.fileName,
                        createdAt: createdAt
                    ))
                }
            }
        }
        artifacts = rebuilt
    }

    /// Condenses a generation prompt into a short label ("a minimal logo for
    /// Kairos, blue" → "a minimal logo for Kairos"). Kept short because the
    /// label goes into the router's system prompt, where every token competes
    /// with the instructions themselves.
    static func label(fromPrompt prompt: String?) -> String? {
        guard let prompt else { return nil }
        let cleaned = prompt
            .replacingOccurrences(of: "\n", with: " ")
            .trimmingCharacters(in: .whitespacesAndNewlines)
        guard !cleaned.isEmpty else { return nil }
        // First sentence only — buildImagePrompt appends a "Visual concept: …"
        // clause that adds length without aiding identification.
        let firstSentence = cleaned.components(separatedBy: ". ").first ?? cleaned
        return firstSentence.count > 60
            ? String(firstSentence.prefix(60)) + "…"
            : firstSentence
    }
}

